export const JOB_REPOSITORY = Symbol('JOB_REPOSITORY');
export const COLUMN_CONFIG_REPOSITORY = Symbol('COLUMN_CONFIG_REPOSITORY');
export const VIDEO_HASH_REPOSITORY = Symbol('VIDEO_HASH_REPOSITORY');
